// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::backup_type::Backup;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `backups`.
///
/// Obtain a handle from the [`BackupsTableAccess::backups`] method on [`super::RemoteTables`],
/// like `ctx.db.backups()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.backups().on_insert(...)`.
pub struct BackupsTableHandle<'ctx> {
    imp: __sdk::TableHandle<Backup>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `backups`.
///
/// Implemented for [`super::RemoteTables`].
pub trait BackupsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`BackupsTableHandle`], which mediates access to the table `backups`.
    fn backups(&self) -> BackupsTableHandle<'_>;
}

impl BackupsTableAccess for super::RemoteTables {
    fn backups(&self) -> BackupsTableHandle<'_> {
        BackupsTableHandle {
            imp: self.imp.get_table::<Backup>("backups"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct BackupsInsertCallbackId(__sdk::CallbackId);
pub struct BackupsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for BackupsTableHandle<'ctx> {
    type Row = Backup;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Backup> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = BackupsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BackupsInsertCallbackId {
        BackupsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: BackupsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = BackupsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BackupsDeleteCallbackId {
        BackupsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: BackupsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct BackupsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for BackupsTableHandle<'ctx> {
    type UpdateCallbackId = BackupsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> BackupsUpdateCallbackId {
        BackupsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: BackupsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `backup_id` unique index on the table `backups`,
/// which allows point queries on the field of the same name
/// via the [`BackupsBackupIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.backups().backup_id().find(...)`.
pub struct BackupsBackupIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Backup, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> BackupsTableHandle<'ctx> {
    /// Get a handle on the `backup_id` unique index on the table `backups`.
    pub fn backup_id(&self) -> BackupsBackupIdUnique<'ctx> {
        BackupsBackupIdUnique {
            imp: self.imp.get_unique_constraint::<String>("backup_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> BackupsBackupIdUnique<'ctx> {
    /// Find the subscribed row whose `backup_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<Backup> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Backup>("backups");
    _table.add_unique_constraint::<String>("backup_id", |row| &row.backup_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Backup>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Backup>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Backup`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait backupsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Backup`.
    fn backups(&self) -> __sdk::__query_builder::Table<Backup>;
}

impl backupsQueryTableAccess for __sdk::QueryTableAccessor {
    fn backups(&self) -> __sdk::__query_builder::Table<Backup> {
        __sdk::__query_builder::Table::new("backups")
    }
}
