// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Backup {
    pub backup_id: String,
    pub kind: String,
    pub status: String,
    pub include_images: bool,
    pub local_path: Option<String>,
    pub remote_filename: Option<String>,
    pub zip_size_bytes: Option<i64>,
    pub quails: i32,
    pub events: i32,
    pub egg_records: i32,
    pub photos_meta: i32,
    pub photos_files_included: i32,
    pub photos_files_missing: i32,
    pub error_message: Option<String>,
    pub owner: String,
    pub created_at: i64,
    pub updated_at: i64,
}

impl __sdk::InModule for Backup {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Backup`.
///
/// Provides typed access to columns for query building.
pub struct BackupCols {
    pub backup_id: __sdk::__query_builder::Col<Backup, String>,
    pub kind: __sdk::__query_builder::Col<Backup, String>,
    pub status: __sdk::__query_builder::Col<Backup, String>,
    pub include_images: __sdk::__query_builder::Col<Backup, bool>,
    pub local_path: __sdk::__query_builder::Col<Backup, Option<String>>,
    pub remote_filename: __sdk::__query_builder::Col<Backup, Option<String>>,
    pub zip_size_bytes: __sdk::__query_builder::Col<Backup, Option<i64>>,
    pub quails: __sdk::__query_builder::Col<Backup, i32>,
    pub events: __sdk::__query_builder::Col<Backup, i32>,
    pub egg_records: __sdk::__query_builder::Col<Backup, i32>,
    pub photos_meta: __sdk::__query_builder::Col<Backup, i32>,
    pub photos_files_included: __sdk::__query_builder::Col<Backup, i32>,
    pub photos_files_missing: __sdk::__query_builder::Col<Backup, i32>,
    pub error_message: __sdk::__query_builder::Col<Backup, Option<String>>,
    pub owner: __sdk::__query_builder::Col<Backup, String>,
    pub created_at: __sdk::__query_builder::Col<Backup, i64>,
    pub updated_at: __sdk::__query_builder::Col<Backup, i64>,
}

impl __sdk::__query_builder::HasCols for Backup {
    type Cols = BackupCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        BackupCols {
            backup_id: __sdk::__query_builder::Col::new(table_name, "backup_id"),
            kind: __sdk::__query_builder::Col::new(table_name, "kind"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            include_images: __sdk::__query_builder::Col::new(table_name, "include_images"),
            local_path: __sdk::__query_builder::Col::new(table_name, "local_path"),
            remote_filename: __sdk::__query_builder::Col::new(table_name, "remote_filename"),
            zip_size_bytes: __sdk::__query_builder::Col::new(table_name, "zip_size_bytes"),
            quails: __sdk::__query_builder::Col::new(table_name, "quails"),
            events: __sdk::__query_builder::Col::new(table_name, "events"),
            egg_records: __sdk::__query_builder::Col::new(table_name, "egg_records"),
            photos_meta: __sdk::__query_builder::Col::new(table_name, "photos_meta"),
            photos_files_included: __sdk::__query_builder::Col::new(
                table_name,
                "photos_files_included",
            ),
            photos_files_missing: __sdk::__query_builder::Col::new(
                table_name,
                "photos_files_missing",
            ),
            error_message: __sdk::__query_builder::Col::new(table_name, "error_message"),
            owner: __sdk::__query_builder::Col::new(table_name, "owner"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `Backup`.
///
/// Provides typed access to indexed columns for query building.
pub struct BackupIxCols {
    pub backup_id: __sdk::__query_builder::IxCol<Backup, String>,
}

impl __sdk::__query_builder::HasIxCols for Backup {
    type IxCols = BackupIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        BackupIxCols {
            backup_id: __sdk::__query_builder::IxCol::new(table_name, "backup_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Backup {}
