// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.0.5 (commit 2dbec5ca66cb9d250f054de469443c2585c573d2).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::create_photo_collection_args_type::CreatePhotoCollectionArgs as CreatePhotoCollectionArgsType;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreatePhotoCollectionArgs {
    pub args: CreatePhotoCollectionArgsType,
}

impl From<CreatePhotoCollectionArgs> for super::Reducer {
    fn from(args: CreatePhotoCollectionArgs) -> Self {
        Self::CreatePhotoCollection { args: args.args }
    }
}

impl __sdk::InModule for CreatePhotoCollectionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_photo_collection`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_photo_collection {
    /// Request that the remote module invoke the reducer `create_photo_collection` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    ///
    /// Use [`create_photo_collection::create_photo_collection_then`] to run a callback after the reducer completes.
    fn create_photo_collection(&self, args: CreatePhotoCollectionArgsType) -> __sdk::Result<()> {
        self.create_photo_collection_then(args, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `create_photo_collection` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn create_photo_collection_then(
        &self,
        args: CreatePhotoCollectionArgsType,
        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl create_photo_collection for super::RemoteReducers {
    fn create_photo_collection_then(
        &self,
        args: CreatePhotoCollectionArgsType,
        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(CreatePhotoCollectionArgs { args }, callback)
    }
}
