// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.0.5 (commit 2dbec5ca66cb9d250f054de469443c2585c573d2).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::create_quail_args_type::CreateQuailArgs as CreateQuailArgsType;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateQuailArgs {
    pub args: CreateQuailArgsType,
}

impl From<CreateQuailArgs> for super::Reducer {
    fn from(args: CreateQuailArgs) -> Self {
        Self::CreateQuail { args: args.args }
    }
}

impl __sdk::InModule for CreateQuailArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_quail`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_quail {
    /// Request that the remote module invoke the reducer `create_quail` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    ///
    /// Use [`create_quail::create_quail_then`] to run a callback after the reducer completes.
    fn create_quail(&self, args: CreateQuailArgsType) -> __sdk::Result<()> {
        self.create_quail_then(args, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `create_quail` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn create_quail_then(
        &self,
        args: CreateQuailArgsType,
        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl create_quail for super::RemoteReducers {
    fn create_quail_then(
        &self,
        args: CreateQuailArgsType,
        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(CreateQuailArgs { args }, callback)
    }
}
