// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.0.5 (commit 2dbec5ca66cb9d250f054de469443c2585c573d2).

#![allow(unused, clippy::all)]

//! Dioxus v0.7 signals and hooks for SpacetimeDB integration.

use super::*;
use ::dioxus::prelude::*;
use ::dioxus::signals::SyncSignal;
use spacetimedb_sdk::{DbContext, Identity, Table, TableWithPrimaryKey};
use std::sync::{Arc, Mutex};

/// Thread-safe wrapper for the database connection.
pub type SharedConnection = Arc<DbConnection>;

/// Container for all table signals, created at root level.
#[derive(Clone)]
pub struct TableSignals {
    pub backups: SyncSignal<Vec<Backup>>,
    pub devices: SyncSignal<Vec<Device>>,
    pub egg_records: SyncSignal<Vec<EggRecord>>,
    pub photo_collections: SyncSignal<Vec<PhotoCollection>>,
    pub photos: SyncSignal<Vec<Photo>>,
    pub quail_events: SyncSignal<Vec<QuailEvent>>,
    pub quails: SyncSignal<Vec<Quail>>,
}

/// Internal state for managing the SpacetimeDB connection.
#[derive(Clone)]
pub struct SpacetimeDbContext {
    /// The database connection (wrapped in Arc for thread-safety).
    pub connection: SyncSignal<Option<SharedConnection>>,
    /// The current connection state.
    pub state: SyncSignal<ConnectionState>,
    /// Error from the last connection attempt, if any.
    pub error: SyncSignal<Option<String>>,
    /// All table signals, created at root level.
    pub tables: TableSignals,
}

/// The current state of the SpacetimeDB connection.
#[derive(Clone, PartialEq, Eq, Debug, Default)]
pub enum ConnectionState {
    #[default]
    Disconnected,
    Connecting,
    Reconnecting {
        attempt: u32,
        delay_ms: u64,
    },
    /// Connected includes the `Identity` assigned by the server and a private access token (JWT)
    /// which can be persisted by the application for future reconnection as the same Identity.
    Connected(Identity, String),
    Error,
}

const RECONNECT_BASE_DELAY_MS: u64 = 400;
const RECONNECT_MAX_DELAY_MS: u64 = 10_000;
const RECONNECT_JITTER_MS: u64 = 300;
const MAX_RECONNECT_ATTEMPTS: u32 = 0;

#[must_use]
fn should_retry_reconnect(attempt: u32) -> bool {
    MAX_RECONNECT_ATTEMPTS == 0 || attempt <= MAX_RECONNECT_ATTEMPTS
}

#[must_use]
fn reconnect_delay_ms(attempt: u32) -> u64 {
    let shift = attempt.min(8);
    let factor = 1u64.checked_shl(shift).unwrap_or(u64::MAX);
    let base_ms = RECONNECT_BASE_DELAY_MS
        .saturating_mul(factor)
        .min(RECONNECT_MAX_DELAY_MS);
    let jitter = (u64::from(attempt).saturating_mul(137)) % RECONNECT_JITTER_MS.max(1);
    base_ms.saturating_add(jitter)
}

#[cfg(not(target_arch = "wasm32"))]
struct ThreadSleep {
    done: Arc<std::sync::atomic::AtomicBool>,
    started: bool,
    delay_ms: u64,
}

#[cfg(not(target_arch = "wasm32"))]
impl ThreadSleep {
    fn new(delay_ms: u64) -> Self {
        Self {
            done: Arc::new(std::sync::atomic::AtomicBool::new(false)),
            started: false,
            delay_ms,
        }
    }
}

#[cfg(not(target_arch = "wasm32"))]
impl std::future::Future for ThreadSleep {
    type Output = ();

    fn poll(
        mut self: std::pin::Pin<&mut Self>,
        cx: &mut std::task::Context<'_>,
    ) -> std::task::Poll<Self::Output> {
        if self.done.load(std::sync::atomic::Ordering::Acquire) {
            return std::task::Poll::Ready(());
        }

        if !self.started {
            self.started = true;
            let done = Arc::clone(&self.done);
            let delay_ms = self.delay_ms;
            let waker = cx.waker().clone();
            std::thread::spawn(move || {
                std::thread::sleep(std::time::Duration::from_millis(delay_ms));
                done.store(true, std::sync::atomic::Ordering::Release);
                waker.wake();
            });
        }

        std::task::Poll::Pending
    }
}

async fn reconnect_sleep(delay_ms: u64) {
    #[cfg(not(target_arch = "wasm32"))]
    {
        ThreadSleep::new(delay_ms).await;
    }
    #[cfg(target_arch = "wasm32")]
    {
        let _ = delay_ms;
    }
}

#[must_use]
fn is_fatal_connection_error(err: &spacetimedb_sdk::Error) -> bool {
    let msg = err.to_string().to_ascii_lowercase();
    msg.contains("unauthorized")
        || msg.contains("forbidden")
        || msg.contains("invalid credentials")
        || msg.contains("invalid token")
        || msg.contains("token expired")
}

/// Initialize the SpacetimeDB context provider at the root of your application.
///
/// This hook must be called at the root component before using any other SpacetimeDB hooks.
/// It creates all table signals at root level to ensure they outlive child components.
///
/// # Arguments
/// * `uri` - The SpacetimeDB server URI
/// * `module_name` - The module name to connect to
/// * `token` - An optional OpenID Connect compliant JSON Web Token (JWT) for authentication.
///   If `None` is passed or this method is not called, SpacetimeDB will generate a new Identity
///   and sign a new private access token for the connection.
#[must_use]
pub fn use_spacetimedb_context_provider(
    uri: &str,
    module_name: &str,
    token: Option<impl ToString>,
) -> SpacetimeDbContext {
    let uri = uri.to_string();
    let module_name = module_name.to_string();
    let token = token.map(|t| t.to_string());
    let active_token: Arc<Mutex<Option<String>>> = Arc::new(Mutex::new(token.clone()));

    let connection: SyncSignal<Option<SharedConnection>> = use_signal_sync(|| None);
    let state: SyncSignal<ConnectionState> = use_signal_sync(|| ConnectionState::Disconnected);
    let error: SyncSignal<Option<String>> = use_signal_sync(|| None);

    let mut table_signals = TableSignals {
        backups: use_signal_sync(Vec::new),
        devices: use_signal_sync(Vec::new),
        egg_records: use_signal_sync(Vec::new),
        photo_collections: use_signal_sync(Vec::new),
        photos: use_signal_sync(Vec::new),
        quail_events: use_signal_sync(Vec::new),
        quails: use_signal_sync(Vec::new),
    };

    let ctx = SpacetimeDbContext {
        connection,
        state,
        error,
        tables: table_signals.clone(),
    };

    use_context_provider(|| ctx.clone());

    use_effect(move || {
        let mut connection = connection;
        let mut state = state;
        let mut error = error;
        let uri = uri.clone();
        let module_name = module_name.clone();
        let active_token = active_token.clone();
        let table_signals = table_signals.clone();

        spawn(async move {
            let mut reconnect_attempt: u32 = 0;

            loop {
                if reconnect_attempt == 0 {
                    state.set(ConnectionState::Connecting);
                } else {
                    let delay_ms = reconnect_delay_ms(reconnect_attempt);
                    state.set(ConnectionState::Reconnecting {
                        attempt: reconnect_attempt,
                        delay_ms,
                    });
                }

                let token_for_build = active_token.lock().ok().and_then(|token| token.clone());

                let disconnect_fatal: Arc<Mutex<bool>> = Arc::new(Mutex::new(false));
                let disconnect_fatal_on_disconnect = disconnect_fatal.clone();

                let mut connection_on_disconnect = connection.clone();
                let mut state_on_disconnect = state.clone();
                let mut error_on_disconnect = error.clone();
                let mut state_on_connect = state.clone();
                let mut error_on_connect = error.clone();
                let mut table_signals_on_connect = table_signals.clone();
                let active_token_on_connect = active_token.clone();

                let conn = match DbConnection::builder()
                    .with_uri(&uri)
                    .with_database_name(&module_name)
                    .with_token(token_for_build)
                    .on_connect(move |conn, identity, token| {
                        // Populate initial rows for backups
                        let current: Vec<Backup> = conn.db.backups().iter().collect();
                        table_signals_on_connect.backups.set(current);

                        // Keep signal in sync on changes
                        conn.db.backups().on_insert(move |ctx, _row| {
                            let updated: Vec<Backup> = ctx.db.backups().iter().collect();
                            table_signals_on_connect.backups.set(updated);
                        });
                        conn.db.backups().on_update(move |ctx, _old, _new| {
                            let updated: Vec<Backup> = ctx.db.backups().iter().collect();
                            table_signals_on_connect.backups.set(updated);
                        });
                        conn.db.backups().on_delete(move |ctx, _row| {
                            let updated: Vec<Backup> = ctx.db.backups().iter().collect();
                            table_signals_on_connect.backups.set(updated);
                        });
                        // Populate initial rows for devices
                        let current: Vec<Device> = conn.db.devices().iter().collect();
                        table_signals_on_connect.devices.set(current);

                        // Keep signal in sync on changes
                        conn.db.devices().on_insert(move |ctx, _row| {
                            let updated: Vec<Device> = ctx.db.devices().iter().collect();
                            table_signals_on_connect.devices.set(updated);
                        });
                        conn.db.devices().on_update(move |ctx, _old, _new| {
                            let updated: Vec<Device> = ctx.db.devices().iter().collect();
                            table_signals_on_connect.devices.set(updated);
                        });
                        conn.db.devices().on_delete(move |ctx, _row| {
                            let updated: Vec<Device> = ctx.db.devices().iter().collect();
                            table_signals_on_connect.devices.set(updated);
                        });
                        // Populate initial rows for egg_records
                        let current: Vec<EggRecord> = conn.db.egg_records().iter().collect();
                        table_signals_on_connect.egg_records.set(current);

                        // Keep signal in sync on changes
                        conn.db.egg_records().on_insert(move |ctx, _row| {
                            let updated: Vec<EggRecord> = ctx.db.egg_records().iter().collect();
                            table_signals_on_connect.egg_records.set(updated);
                        });
                        conn.db.egg_records().on_update(move |ctx, _old, _new| {
                            let updated: Vec<EggRecord> = ctx.db.egg_records().iter().collect();
                            table_signals_on_connect.egg_records.set(updated);
                        });
                        conn.db.egg_records().on_delete(move |ctx, _row| {
                            let updated: Vec<EggRecord> = ctx.db.egg_records().iter().collect();
                            table_signals_on_connect.egg_records.set(updated);
                        });
                        // Populate initial rows for photo_collections
                        let current: Vec<PhotoCollection> =
                            conn.db.photo_collections().iter().collect();
                        table_signals_on_connect.photo_collections.set(current);

                        // Keep signal in sync on changes
                        conn.db.photo_collections().on_insert(move |ctx, _row| {
                            let updated: Vec<PhotoCollection> =
                                ctx.db.photo_collections().iter().collect();
                            table_signals_on_connect.photo_collections.set(updated);
                        });
                        conn.db
                            .photo_collections()
                            .on_update(move |ctx, _old, _new| {
                                let updated: Vec<PhotoCollection> =
                                    ctx.db.photo_collections().iter().collect();
                                table_signals_on_connect.photo_collections.set(updated);
                            });
                        conn.db.photo_collections().on_delete(move |ctx, _row| {
                            let updated: Vec<PhotoCollection> =
                                ctx.db.photo_collections().iter().collect();
                            table_signals_on_connect.photo_collections.set(updated);
                        });
                        // Populate initial rows for photos
                        let current: Vec<Photo> = conn.db.photos().iter().collect();
                        table_signals_on_connect.photos.set(current);

                        // Keep signal in sync on changes
                        conn.db.photos().on_insert(move |ctx, _row| {
                            let updated: Vec<Photo> = ctx.db.photos().iter().collect();
                            table_signals_on_connect.photos.set(updated);
                        });
                        conn.db.photos().on_update(move |ctx, _old, _new| {
                            let updated: Vec<Photo> = ctx.db.photos().iter().collect();
                            table_signals_on_connect.photos.set(updated);
                        });
                        conn.db.photos().on_delete(move |ctx, _row| {
                            let updated: Vec<Photo> = ctx.db.photos().iter().collect();
                            table_signals_on_connect.photos.set(updated);
                        });
                        // Populate initial rows for quail_events
                        let current: Vec<QuailEvent> = conn.db.quail_events().iter().collect();
                        table_signals_on_connect.quail_events.set(current);

                        // Keep signal in sync on changes
                        conn.db.quail_events().on_insert(move |ctx, _row| {
                            let updated: Vec<QuailEvent> = ctx.db.quail_events().iter().collect();
                            table_signals_on_connect.quail_events.set(updated);
                        });
                        conn.db.quail_events().on_update(move |ctx, _old, _new| {
                            let updated: Vec<QuailEvent> = ctx.db.quail_events().iter().collect();
                            table_signals_on_connect.quail_events.set(updated);
                        });
                        conn.db.quail_events().on_delete(move |ctx, _row| {
                            let updated: Vec<QuailEvent> = ctx.db.quail_events().iter().collect();
                            table_signals_on_connect.quail_events.set(updated);
                        });
                        // Populate initial rows for quails
                        let current: Vec<Quail> = conn.db.quails().iter().collect();
                        table_signals_on_connect.quails.set(current);

                        // Keep signal in sync on changes
                        conn.db.quails().on_insert(move |ctx, _row| {
                            let updated: Vec<Quail> = ctx.db.quails().iter().collect();
                            table_signals_on_connect.quails.set(updated);
                        });
                        conn.db.quails().on_update(move |ctx, _old, _new| {
                            let updated: Vec<Quail> = ctx.db.quails().iter().collect();
                            table_signals_on_connect.quails.set(updated);
                        });
                        conn.db.quails().on_delete(move |ctx, _row| {
                            let updated: Vec<Quail> = ctx.db.quails().iter().collect();
                            table_signals_on_connect.quails.set(updated);
                        });
                        if let Ok(mut token_store) = active_token_on_connect.lock() {
                            *token_store = Some(token.to_string());
                        }

                        // Store the assigned Identity and private access token in state so the app
                        // can persist the token (JWT) and reuse it for future reconnections via `with_token`.
                        error_on_connect.set(None);
                        state_on_connect
                            .set(ConnectionState::Connected(identity, token.to_string()));
                    })
                    .on_disconnect(move |_ctx, err: Option<spacetimedb_sdk::Error>| {
                        connection_on_disconnect.set(None);
                        if let Some(e) = err {
                            error_on_disconnect.set(Some::<String>(e.to_string()));
                            if is_fatal_connection_error(&e) {
                                if let Ok(mut fatal) = disconnect_fatal_on_disconnect.lock() {
                                    *fatal = true;
                                }
                            }
                        }
                        state_on_disconnect.set(ConnectionState::Disconnected);
                    })
                    .build()
                {
                    Ok(conn) => conn,
                    Err(e) => {
                        connection.set(None);
                        error.set(Some::<String>(e.to_string()));
                        if is_fatal_connection_error(&e) {
                            state.set(ConnectionState::Error);
                            break;
                        }
                        reconnect_attempt = reconnect_attempt.saturating_add(1);
                        if !should_retry_reconnect(reconnect_attempt) {
                            state.set(ConnectionState::Error);
                            break;
                        }
                        let delay_ms = reconnect_delay_ms(reconnect_attempt);
                        state.set(ConnectionState::Reconnecting {
                            attempt: reconnect_attempt,
                            delay_ms,
                        });
                        reconnect_sleep(delay_ms).await;
                        continue;
                    }
                };

                let shared_conn: Arc<DbConnection> = Arc::new(conn);
                connection.set(Some(shared_conn.clone()));
                reconnect_attempt = 0;

                let run_result = shared_conn.run_async().await;
                connection.set(None);

                let disconnected_with_fatal_error = disconnect_fatal
                    .lock()
                    .ok()
                    .map(|fatal| *fatal)
                    .unwrap_or(false);
                if disconnected_with_fatal_error {
                    state.set(ConnectionState::Error);
                    break;
                }

                if let Err(e) = run_result {
                    error.set(Some::<String>(e.to_string()));
                    if is_fatal_connection_error(&e) {
                        state.set(ConnectionState::Error);
                        break;
                    }
                }

                reconnect_attempt = reconnect_attempt.saturating_add(1);
                if !should_retry_reconnect(reconnect_attempt) {
                    state.set(ConnectionState::Error);
                    break;
                }

                let delay_ms = reconnect_delay_ms(reconnect_attempt);
                state.set(ConnectionState::Reconnecting {
                    attempt: reconnect_attempt,
                    delay_ms,
                });
                reconnect_sleep(delay_ms).await;
            }
        });
    });

    ctx
}

/// Get the SpacetimeDB context from a parent component.
#[must_use]
pub fn use_spacetimedb_context() -> SpacetimeDbContext {
    use_context::<SpacetimeDbContext>()
}

/// Get the current database connection, if connected.
#[must_use]
pub fn use_connection() -> SyncSignal<Option<SharedConnection>> {
    let ctx = use_spacetimedb_context();
    ctx.connection
}

/// Subscribe to a set of SQL queries.
///
/// Re-subscribes automatically whenever the connection instance changes
/// (initial connect, or reconnect after a network interruption).
/// Avoids duplicate subscriptions while the connection is stable.
/// Subscription errors are printed to stderr for diagnosis.
pub fn use_subscription(queries: &[&str]) {
    let queries: Vec<String> = queries.iter().map(|s| s.to_string()).collect();
    let conn_signal = use_connection();

    // Stores the Arc pointer of the last successfully-subscribed connection.
    // Using peek() inside the effect keeps this read non-reactive (no infinite loop).
    let last_conn: SyncSignal<Option<SharedConnection>> = use_signal_sync(|| None);

    use_effect(move || {
        // transition (None->Some on connect, Some->None on disconnect, Some(a)->Some(b) on reconnect).
        let current = conn_signal();
        let mut last = last_conn;

        match current.as_ref() {
            None => {
                // Connection lost: clear the tracker so the next connection
                // instance will trigger a fresh subscribe.
                // peek() avoids creating a reactive dependency that would loop.
                if last.peek().is_some() {
                    last.set(None);
                }
            }
            Some(conn) => {
                // peek() reads last without subscribing to it reactively.
                if last
                    .peek()
                    .as_ref()
                    .map(|prev| Arc::ptr_eq(prev, conn))
                    .unwrap_or(false)
                {
                    // Same connection instance – already subscribed, nothing to do.
                    return;
                }
                // New or reconnected instance – store it and subscribe.
                last.set(Some(conn.clone()));
                let queries = queries.clone();
                conn.subscription_builder()
                    .on_applied(|_ctx| {})
                    .on_error(|_ctx, err| {
                        eprintln!("[spacetimedb] subscription error: {err}");
                    })
                    .subscribe(queries);
            }
        }
    });
}

// --- Table hooks ---

/// Get a reactive signal containing all rows of the `backups` table.
#[must_use]
pub fn use_table_backups() -> SyncSignal<Vec<Backup>> {
    let ctx = use_spacetimedb_context();
    ctx.tables.backups
}

/// Get a reactive signal containing all rows of the `devices` table.
#[must_use]
pub fn use_table_devices() -> SyncSignal<Vec<Device>> {
    let ctx = use_spacetimedb_context();
    ctx.tables.devices
}

/// Get a reactive signal containing all rows of the `egg_records` table.
#[must_use]
pub fn use_table_egg_records() -> SyncSignal<Vec<EggRecord>> {
    let ctx = use_spacetimedb_context();
    ctx.tables.egg_records
}

/// Get a reactive signal containing all rows of the `photo_collections` table.
#[must_use]
pub fn use_table_photo_collections() -> SyncSignal<Vec<PhotoCollection>> {
    let ctx = use_spacetimedb_context();
    ctx.tables.photo_collections
}

/// Get a reactive signal containing all rows of the `photos` table.
#[must_use]
pub fn use_table_photos() -> SyncSignal<Vec<Photo>> {
    let ctx = use_spacetimedb_context();
    ctx.tables.photos
}

/// Get a reactive signal containing all rows of the `quail_events` table.
#[must_use]
pub fn use_table_quail_events() -> SyncSignal<Vec<QuailEvent>> {
    let ctx = use_spacetimedb_context();
    ctx.tables.quail_events
}

/// Get a reactive signal containing all rows of the `quails` table.
#[must_use]
pub fn use_table_quails() -> SyncSignal<Vec<Quail>> {
    let ctx = use_spacetimedb_context();
    ctx.tables.quails
}

// --- Reducer hooks ---

/// Get a callback to invoke the `create_backup_started` reducer.
#[must_use]
pub fn use_reducer_create_backup_started()
-> impl Fn(create_backup_started_args_type::CreateBackupStartedArgs) -> spacetimedb_sdk::Result<()>
+ Clone
+ 'static {
    let conn_signal = use_connection();

    move |args: create_backup_started_args_type::CreateBackupStartedArgs| {
        if let Some(conn) = conn_signal().as_ref() {
            conn.reducers.create_backup_started(args)
        } else {
            Err(spacetimedb_sdk::Error::Disconnected)
        }
    }
}

/// Get a callback to invoke the `create_event` reducer.
#[must_use]
pub fn use_reducer_create_event()
-> impl Fn(create_event_args_type::CreateEventArgs) -> spacetimedb_sdk::Result<()> + Clone + 'static
{
    let conn_signal = use_connection();

    move |args: create_event_args_type::CreateEventArgs| {
        if let Some(conn) = conn_signal().as_ref() {
            conn.reducers.create_event(args)
        } else {
            Err(spacetimedb_sdk::Error::Disconnected)
        }
    }
}

/// Get a callback to invoke the `create_photo` reducer.
#[must_use]
pub fn use_reducer_create_photo()
-> impl Fn(create_photo_args_type::CreatePhotoArgs) -> spacetimedb_sdk::Result<()> + Clone + 'static
{
    let conn_signal = use_connection();

    move |args: create_photo_args_type::CreatePhotoArgs| {
        if let Some(conn) = conn_signal().as_ref() {
            conn.reducers.create_photo(args)
        } else {
            Err(spacetimedb_sdk::Error::Disconnected)
        }
    }
}

/// Get a callback to invoke the `create_photo_collection` reducer.
#[must_use]
pub fn use_reducer_create_photo_collection()
-> impl Fn(create_photo_collection_args_type::CreatePhotoCollectionArgs) -> spacetimedb_sdk::Result<()>
+ Clone
+ 'static {
    let conn_signal = use_connection();

    move |args: create_photo_collection_args_type::CreatePhotoCollectionArgs| {
        if let Some(conn) = conn_signal().as_ref() {
            conn.reducers.create_photo_collection(args)
        } else {
            Err(spacetimedb_sdk::Error::Disconnected)
        }
    }
}

/// Get a callback to invoke the `create_quail` reducer.
#[must_use]
pub fn use_reducer_create_quail()
-> impl Fn(create_quail_args_type::CreateQuailArgs) -> spacetimedb_sdk::Result<()> + Clone + 'static
{
    let conn_signal = use_connection();

    move |args: create_quail_args_type::CreateQuailArgs| {
        if let Some(conn) = conn_signal().as_ref() {
            conn.reducers.create_quail(args)
        } else {
            Err(spacetimedb_sdk::Error::Disconnected)
        }
    }
}

/// Get a callback to invoke the `delete_device` reducer.
#[must_use]
pub fn use_reducer_delete_device()
-> impl Fn(String) -> spacetimedb_sdk::Result<()> + Clone + 'static {
    let conn_signal = use_connection();

    move |device_id: String| {
        if let Some(conn) = conn_signal().as_ref() {
            conn.reducers.delete_device(device_id)
        } else {
            Err(spacetimedb_sdk::Error::Disconnected)
        }
    }
}

/// Get a callback to invoke the `delete_egg_record` reducer.
#[must_use]
pub fn use_reducer_delete_egg_record()
-> impl Fn(String) -> spacetimedb_sdk::Result<()> + Clone + 'static {
    let conn_signal = use_connection();

    move |uuid: String| {
        if let Some(conn) = conn_signal().as_ref() {
            conn.reducers.delete_egg_record(uuid)
        } else {
            Err(spacetimedb_sdk::Error::Disconnected)
        }
    }
}

/// Get a callback to invoke the `delete_event` reducer.
#[must_use]
pub fn use_reducer_delete_event() -> impl Fn(String) -> spacetimedb_sdk::Result<()> + Clone + 'static
{
    let conn_signal = use_connection();

    move |uuid: String| {
        if let Some(conn) = conn_signal().as_ref() {
            conn.reducers.delete_event(uuid)
        } else {
            Err(spacetimedb_sdk::Error::Disconnected)
        }
    }
}

/// Get a callback to invoke the `delete_photo` reducer.
#[must_use]
pub fn use_reducer_delete_photo() -> impl Fn(String) -> spacetimedb_sdk::Result<()> + Clone + 'static
{
    let conn_signal = use_connection();

    move |uuid: String| {
        if let Some(conn) = conn_signal().as_ref() {
            conn.reducers.delete_photo(uuid)
        } else {
            Err(spacetimedb_sdk::Error::Disconnected)
        }
    }
}

/// Get a callback to invoke the `delete_photo_collection` reducer.
#[must_use]
pub fn use_reducer_delete_photo_collection()
-> impl Fn(String) -> spacetimedb_sdk::Result<()> + Clone + 'static {
    let conn_signal = use_connection();

    move |uuid: String| {
        if let Some(conn) = conn_signal().as_ref() {
            conn.reducers.delete_photo_collection(uuid)
        } else {
            Err(spacetimedb_sdk::Error::Disconnected)
        }
    }
}

/// Get a callback to invoke the `delete_quail` reducer.
#[must_use]
pub fn use_reducer_delete_quail() -> impl Fn(String) -> spacetimedb_sdk::Result<()> + Clone + 'static
{
    let conn_signal = use_connection();

    move |uuid: String| {
        if let Some(conn) = conn_signal().as_ref() {
            conn.reducers.delete_quail(uuid)
        } else {
            Err(spacetimedb_sdk::Error::Disconnected)
        }
    }
}

/// Get a callback to invoke the `finish_backup` reducer.
#[must_use]
pub fn use_reducer_finish_backup()
-> impl Fn(finish_backup_args_type::FinishBackupArgs) -> spacetimedb_sdk::Result<()> + Clone + 'static
{
    let conn_signal = use_connection();

    move |args: finish_backup_args_type::FinishBackupArgs| {
        if let Some(conn) = conn_signal().as_ref() {
            conn.reducers.finish_backup(args)
        } else {
            Err(spacetimedb_sdk::Error::Disconnected)
        }
    }
}

/// Get a callback to invoke the `register_device` reducer.
#[must_use]
pub fn use_reducer_register_device()
-> impl Fn(register_device_args_type::RegisterDeviceArgs) -> spacetimedb_sdk::Result<()>
+ Clone
+ 'static {
    let conn_signal = use_connection();

    move |args: register_device_args_type::RegisterDeviceArgs| {
        if let Some(conn) = conn_signal().as_ref() {
            conn.reducers.register_device(args)
        } else {
            Err(spacetimedb_sdk::Error::Disconnected)
        }
    }
}

/// Get a callback to invoke the `set_quail_photo` reducer.
#[must_use]
pub fn use_reducer_set_quail_photo()
-> impl Fn(String, Option<String>) -> spacetimedb_sdk::Result<()> + Clone + 'static {
    let conn_signal = use_connection();

    move |quail_uuid: String, photo_uuid: Option<String>| {
        if let Some(conn) = conn_signal().as_ref() {
            conn.reducers.set_quail_photo(quail_uuid, photo_uuid)
        } else {
            Err(spacetimedb_sdk::Error::Disconnected)
        }
    }
}

/// Get a callback to invoke the `update_device` reducer.
#[must_use]
pub fn use_reducer_update_device()
-> impl Fn(update_device_args_type::UpdateDeviceArgs) -> spacetimedb_sdk::Result<()> + Clone + 'static
{
    let conn_signal = use_connection();

    move |args: update_device_args_type::UpdateDeviceArgs| {
        if let Some(conn) = conn_signal().as_ref() {
            conn.reducers.update_device(args)
        } else {
            Err(spacetimedb_sdk::Error::Disconnected)
        }
    }
}

/// Get a callback to invoke the `update_event` reducer.
#[must_use]
pub fn use_reducer_update_event()
-> impl Fn(update_event_args_type::UpdateEventArgs) -> spacetimedb_sdk::Result<()> + Clone + 'static
{
    let conn_signal = use_connection();

    move |args: update_event_args_type::UpdateEventArgs| {
        if let Some(conn) = conn_signal().as_ref() {
            conn.reducers.update_event(args)
        } else {
            Err(spacetimedb_sdk::Error::Disconnected)
        }
    }
}

/// Get a callback to invoke the `update_photo_collection` reducer.
#[must_use]
pub fn use_reducer_update_photo_collection()
-> impl Fn(update_photo_collection_args_type::UpdatePhotoCollectionArgs) -> spacetimedb_sdk::Result<()>
+ Clone
+ 'static {
    let conn_signal = use_connection();

    move |args: update_photo_collection_args_type::UpdatePhotoCollectionArgs| {
        if let Some(conn) = conn_signal().as_ref() {
            conn.reducers.update_photo_collection(args)
        } else {
            Err(spacetimedb_sdk::Error::Disconnected)
        }
    }
}

/// Get a callback to invoke the `update_photo_sync_status` reducer.
#[must_use]
pub fn use_reducer_update_photo_sync_status()
-> impl Fn(update_photo_sync_status_args_type::UpdatePhotoSyncStatusArgs) -> spacetimedb_sdk::Result<()>
+ Clone
+ 'static {
    let conn_signal = use_connection();

    move |args: update_photo_sync_status_args_type::UpdatePhotoSyncStatusArgs| {
        if let Some(conn) = conn_signal().as_ref() {
            conn.reducers.update_photo_sync_status(args)
        } else {
            Err(spacetimedb_sdk::Error::Disconnected)
        }
    }
}

/// Get a callback to invoke the `update_photo_version` reducer.
#[must_use]
pub fn use_reducer_update_photo_version()
-> impl Fn(update_photo_version_args_type::UpdatePhotoVersionArgs) -> spacetimedb_sdk::Result<()>
+ Clone
+ 'static {
    let conn_signal = use_connection();

    move |args: update_photo_version_args_type::UpdatePhotoVersionArgs| {
        if let Some(conn) = conn_signal().as_ref() {
            conn.reducers.update_photo_version(args)
        } else {
            Err(spacetimedb_sdk::Error::Disconnected)
        }
    }
}

/// Get a callback to invoke the `update_quail` reducer.
#[must_use]
pub fn use_reducer_update_quail()
-> impl Fn(update_quail_args_type::UpdateQuailArgs) -> spacetimedb_sdk::Result<()> + Clone + 'static
{
    let conn_signal = use_connection();

    move |args: update_quail_args_type::UpdateQuailArgs| {
        if let Some(conn) = conn_signal().as_ref() {
            conn.reducers.update_quail(args)
        } else {
            Err(spacetimedb_sdk::Error::Disconnected)
        }
    }
}

/// Get a callback to invoke the `upsert_egg_record` reducer.
#[must_use]
pub fn use_reducer_upsert_egg_record()
-> impl Fn(upsert_egg_record_args_type::UpsertEggRecordArgs) -> spacetimedb_sdk::Result<()>
+ Clone
+ 'static {
    let conn_signal = use_connection();

    move |args: upsert_egg_record_args_type::UpsertEggRecordArgs| {
        if let Some(conn) = conn_signal().as_ref() {
            conn.reducers.upsert_egg_record(args)
        } else {
            Err(spacetimedb_sdk::Error::Disconnected)
        }
    }
}

// --- Connection state hooks ---

/// Get a reactive signal for the current connection state.
#[must_use]
pub fn use_connection_state() -> SyncSignal<ConnectionState> {
    let ctx = use_spacetimedb_context();
    ctx.state
}

/// Get a reactive signal for the current connection error, if any.
#[must_use]
pub fn use_connection_error() -> SyncSignal<Option<String>> {
    let ctx = use_spacetimedb_context();
    ctx.error
}
