// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::egg_record_type::EggRecord;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `egg_records`.
///
/// Obtain a handle from the [`EggRecordsTableAccess::egg_records`] method on [`super::RemoteTables`],
/// like `ctx.db.egg_records()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.egg_records().on_insert(...)`.
pub struct EggRecordsTableHandle<'ctx> {
    imp: __sdk::TableHandle<EggRecord>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `egg_records`.
///
/// Implemented for [`super::RemoteTables`].
pub trait EggRecordsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`EggRecordsTableHandle`], which mediates access to the table `egg_records`.
    fn egg_records(&self) -> EggRecordsTableHandle<'_>;
}

impl EggRecordsTableAccess for super::RemoteTables {
    fn egg_records(&self) -> EggRecordsTableHandle<'_> {
        EggRecordsTableHandle {
            imp: self.imp.get_table::<EggRecord>("egg_records"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct EggRecordsInsertCallbackId(__sdk::CallbackId);
pub struct EggRecordsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for EggRecordsTableHandle<'ctx> {
    type Row = EggRecord;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = EggRecord> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = EggRecordsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EggRecordsInsertCallbackId {
        EggRecordsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: EggRecordsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = EggRecordsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EggRecordsDeleteCallbackId {
        EggRecordsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: EggRecordsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct EggRecordsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for EggRecordsTableHandle<'ctx> {
    type UpdateCallbackId = EggRecordsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> EggRecordsUpdateCallbackId {
        EggRecordsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: EggRecordsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `uuid` unique index on the table `egg_records`,
/// which allows point queries on the field of the same name
/// via the [`EggRecordsUuidUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.egg_records().uuid().find(...)`.
pub struct EggRecordsUuidUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<EggRecord, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> EggRecordsTableHandle<'ctx> {
    /// Get a handle on the `uuid` unique index on the table `egg_records`.
    pub fn uuid(&self) -> EggRecordsUuidUnique<'ctx> {
        EggRecordsUuidUnique {
            imp: self.imp.get_unique_constraint::<String>("uuid"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> EggRecordsUuidUnique<'ctx> {
    /// Find the subscribed row whose `uuid` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<EggRecord> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<EggRecord>("egg_records");
    _table.add_unique_constraint::<String>("uuid", |row| &row.uuid);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<EggRecord>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<EggRecord>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `EggRecord`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait egg_recordsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `EggRecord`.
    fn egg_records(&self) -> __sdk::__query_builder::Table<EggRecord>;
}

impl egg_recordsQueryTableAccess for __sdk::QueryTableAccessor {
    fn egg_records(&self) -> __sdk::__query_builder::Table<EggRecord> {
        __sdk::__query_builder::Table::new("egg_records")
    }
}
