// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct FinishBackupArgs {
    pub backup_id: String,
    pub status: String,
    pub local_path: Option<String>,
    pub remote_filename: Option<String>,
    pub zip_size_bytes: Option<i64>,
    pub quails: i32,
    pub events: i32,
    pub egg_records: i32,
    pub photos_meta: i32,
    pub photos_files_included: i32,
    pub photos_files_missing: i32,
    pub error_message: Option<String>,
}

impl __sdk::InModule for FinishBackupArgs {
    type Module = super::RemoteModule;
}
