// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.0.3 (commit 62812a0ed757d82548fcd15b51a6ffda659f80c2).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::finish_backup_args_type::FinishBackupArgs as FinishBackupArgsType;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct FinishBackupArgs {
    pub args: FinishBackupArgsType,
}

impl From<FinishBackupArgs> for super::Reducer {
    fn from(args: FinishBackupArgs) -> Self {
        Self::FinishBackup { args: args.args }
    }
}

impl __sdk::InModule for FinishBackupArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `finish_backup`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait finish_backup {
    /// Request that the remote module invoke the reducer `finish_backup` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    ///
    /// Use [`finish_backup::finish_backup_then`] to run a callback after the reducer completes.
    fn finish_backup(&self, args: FinishBackupArgsType) -> __sdk::Result<()> {
        self.finish_backup_then(args, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `finish_backup` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn finish_backup_then(
        &self,
        args: FinishBackupArgsType,
        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl finish_backup for super::RemoteReducers {
    fn finish_backup_then(
        &self,
        args: FinishBackupArgsType,
        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(FinishBackupArgs { args }, callback)
    }
}
