// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::photo_collection_type::PhotoCollection;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `photo_collections`.
///
/// Obtain a handle from the [`PhotoCollectionsTableAccess::photo_collections`] method on [`super::RemoteTables`],
/// like `ctx.db.photo_collections()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.photo_collections().on_insert(...)`.
pub struct PhotoCollectionsTableHandle<'ctx> {
    imp: __sdk::TableHandle<PhotoCollection>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `photo_collections`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PhotoCollectionsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PhotoCollectionsTableHandle`], which mediates access to the table `photo_collections`.
    fn photo_collections(&self) -> PhotoCollectionsTableHandle<'_>;
}

impl PhotoCollectionsTableAccess for super::RemoteTables {
    fn photo_collections(&self) -> PhotoCollectionsTableHandle<'_> {
        PhotoCollectionsTableHandle {
            imp: self.imp.get_table::<PhotoCollection>("photo_collections"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PhotoCollectionsInsertCallbackId(__sdk::CallbackId);
pub struct PhotoCollectionsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PhotoCollectionsTableHandle<'ctx> {
    type Row = PhotoCollection;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PhotoCollection> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PhotoCollectionsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PhotoCollectionsInsertCallbackId {
        PhotoCollectionsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PhotoCollectionsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PhotoCollectionsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PhotoCollectionsDeleteCallbackId {
        PhotoCollectionsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PhotoCollectionsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct PhotoCollectionsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PhotoCollectionsTableHandle<'ctx> {
    type UpdateCallbackId = PhotoCollectionsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PhotoCollectionsUpdateCallbackId {
        PhotoCollectionsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PhotoCollectionsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `uuid` unique index on the table `photo_collections`,
/// which allows point queries on the field of the same name
/// via the [`PhotoCollectionsUuidUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.photo_collections().uuid().find(...)`.
pub struct PhotoCollectionsUuidUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PhotoCollection, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PhotoCollectionsTableHandle<'ctx> {
    /// Get a handle on the `uuid` unique index on the table `photo_collections`.
    pub fn uuid(&self) -> PhotoCollectionsUuidUnique<'ctx> {
        PhotoCollectionsUuidUnique {
            imp: self.imp.get_unique_constraint::<String>("uuid"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PhotoCollectionsUuidUnique<'ctx> {
    /// Find the subscribed row whose `uuid` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<PhotoCollection> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PhotoCollection>("photo_collections");
    _table.add_unique_constraint::<String>("uuid", |row| &row.uuid);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<PhotoCollection>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PhotoCollection>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `PhotoCollection`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait photo_collectionsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `PhotoCollection`.
    fn photo_collections(&self) -> __sdk::__query_builder::Table<PhotoCollection>;
}

impl photo_collectionsQueryTableAccess for __sdk::QueryTableAccessor {
    fn photo_collections(&self) -> __sdk::__query_builder::Table<PhotoCollection> {
        __sdk::__query_builder::Table::new("photo_collections")
    }
}
