// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Photo {
    pub uuid: String,
    pub collection_uuid: String,
    pub relative_path: String,
    pub sync_status: String,
    pub sync_error: Option<String>,
    pub last_sync_attempt: Option<i64>,
    pub retry_count: i32,
    pub device_id: String,
    pub owner: String,
    pub created_at: i64,
    pub updated_at: i64,
    pub version: i32,
    pub is_original: bool,
}

impl __sdk::InModule for Photo {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Photo`.
///
/// Provides typed access to columns for query building.
pub struct PhotoCols {
    pub uuid: __sdk::__query_builder::Col<Photo, String>,
    pub collection_uuid: __sdk::__query_builder::Col<Photo, String>,
    pub relative_path: __sdk::__query_builder::Col<Photo, String>,
    pub sync_status: __sdk::__query_builder::Col<Photo, String>,
    pub sync_error: __sdk::__query_builder::Col<Photo, Option<String>>,
    pub last_sync_attempt: __sdk::__query_builder::Col<Photo, Option<i64>>,
    pub retry_count: __sdk::__query_builder::Col<Photo, i32>,
    pub device_id: __sdk::__query_builder::Col<Photo, String>,
    pub owner: __sdk::__query_builder::Col<Photo, String>,
    pub created_at: __sdk::__query_builder::Col<Photo, i64>,
    pub updated_at: __sdk::__query_builder::Col<Photo, i64>,
    pub version: __sdk::__query_builder::Col<Photo, i32>,
    pub is_original: __sdk::__query_builder::Col<Photo, bool>,
}

impl __sdk::__query_builder::HasCols for Photo {
    type Cols = PhotoCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PhotoCols {
            uuid: __sdk::__query_builder::Col::new(table_name, "uuid"),
            collection_uuid: __sdk::__query_builder::Col::new(table_name, "collection_uuid"),
            relative_path: __sdk::__query_builder::Col::new(table_name, "relative_path"),
            sync_status: __sdk::__query_builder::Col::new(table_name, "sync_status"),
            sync_error: __sdk::__query_builder::Col::new(table_name, "sync_error"),
            last_sync_attempt: __sdk::__query_builder::Col::new(table_name, "last_sync_attempt"),
            retry_count: __sdk::__query_builder::Col::new(table_name, "retry_count"),
            device_id: __sdk::__query_builder::Col::new(table_name, "device_id"),
            owner: __sdk::__query_builder::Col::new(table_name, "owner"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
            version: __sdk::__query_builder::Col::new(table_name, "version"),
            is_original: __sdk::__query_builder::Col::new(table_name, "is_original"),
        }
    }
}

/// Indexed column accessor struct for the table `Photo`.
///
/// Provides typed access to indexed columns for query building.
pub struct PhotoIxCols {
    pub uuid: __sdk::__query_builder::IxCol<Photo, String>,
}

impl __sdk::__query_builder::HasIxCols for Photo {
    type IxCols = PhotoIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PhotoIxCols {
            uuid: __sdk::__query_builder::IxCol::new(table_name, "uuid"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Photo {}
