// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::photo_type::Photo;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `photos`.
///
/// Obtain a handle from the [`PhotosTableAccess::photos`] method on [`super::RemoteTables`],
/// like `ctx.db.photos()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.photos().on_insert(...)`.
pub struct PhotosTableHandle<'ctx> {
    imp: __sdk::TableHandle<Photo>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `photos`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PhotosTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PhotosTableHandle`], which mediates access to the table `photos`.
    fn photos(&self) -> PhotosTableHandle<'_>;
}

impl PhotosTableAccess for super::RemoteTables {
    fn photos(&self) -> PhotosTableHandle<'_> {
        PhotosTableHandle {
            imp: self.imp.get_table::<Photo>("photos"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PhotosInsertCallbackId(__sdk::CallbackId);
pub struct PhotosDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PhotosTableHandle<'ctx> {
    type Row = Photo;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Photo> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PhotosInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PhotosInsertCallbackId {
        PhotosInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PhotosInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PhotosDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PhotosDeleteCallbackId {
        PhotosDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PhotosDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct PhotosUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PhotosTableHandle<'ctx> {
    type UpdateCallbackId = PhotosUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PhotosUpdateCallbackId {
        PhotosUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PhotosUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `uuid` unique index on the table `photos`,
/// which allows point queries on the field of the same name
/// via the [`PhotosUuidUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.photos().uuid().find(...)`.
pub struct PhotosUuidUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Photo, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PhotosTableHandle<'ctx> {
    /// Get a handle on the `uuid` unique index on the table `photos`.
    pub fn uuid(&self) -> PhotosUuidUnique<'ctx> {
        PhotosUuidUnique {
            imp: self.imp.get_unique_constraint::<String>("uuid"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PhotosUuidUnique<'ctx> {
    /// Find the subscribed row whose `uuid` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<Photo> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Photo>("photos");
    _table.add_unique_constraint::<String>("uuid", |row| &row.uuid);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Photo>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Photo>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Photo`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait photosQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Photo`.
    fn photos(&self) -> __sdk::__query_builder::Table<Photo>;
}

impl photosQueryTableAccess for __sdk::QueryTableAccessor {
    fn photos(&self) -> __sdk::__query_builder::Table<Photo> {
        __sdk::__query_builder::Table::new("photos")
    }
}
