// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::quail_event_type::QuailEvent;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `quail_events`.
///
/// Obtain a handle from the [`QuailEventsTableAccess::quail_events`] method on [`super::RemoteTables`],
/// like `ctx.db.quail_events()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.quail_events().on_insert(...)`.
pub struct QuailEventsTableHandle<'ctx> {
    imp: __sdk::TableHandle<QuailEvent>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `quail_events`.
///
/// Implemented for [`super::RemoteTables`].
pub trait QuailEventsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`QuailEventsTableHandle`], which mediates access to the table `quail_events`.
    fn quail_events(&self) -> QuailEventsTableHandle<'_>;
}

impl QuailEventsTableAccess for super::RemoteTables {
    fn quail_events(&self) -> QuailEventsTableHandle<'_> {
        QuailEventsTableHandle {
            imp: self.imp.get_table::<QuailEvent>("quail_events"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct QuailEventsInsertCallbackId(__sdk::CallbackId);
pub struct QuailEventsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for QuailEventsTableHandle<'ctx> {
    type Row = QuailEvent;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = QuailEvent> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = QuailEventsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> QuailEventsInsertCallbackId {
        QuailEventsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: QuailEventsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = QuailEventsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> QuailEventsDeleteCallbackId {
        QuailEventsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: QuailEventsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct QuailEventsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for QuailEventsTableHandle<'ctx> {
    type UpdateCallbackId = QuailEventsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> QuailEventsUpdateCallbackId {
        QuailEventsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: QuailEventsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `uuid` unique index on the table `quail_events`,
/// which allows point queries on the field of the same name
/// via the [`QuailEventsUuidUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.quail_events().uuid().find(...)`.
pub struct QuailEventsUuidUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<QuailEvent, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> QuailEventsTableHandle<'ctx> {
    /// Get a handle on the `uuid` unique index on the table `quail_events`.
    pub fn uuid(&self) -> QuailEventsUuidUnique<'ctx> {
        QuailEventsUuidUnique {
            imp: self.imp.get_unique_constraint::<String>("uuid"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> QuailEventsUuidUnique<'ctx> {
    /// Find the subscribed row whose `uuid` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<QuailEvent> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<QuailEvent>("quail_events");
    _table.add_unique_constraint::<String>("uuid", |row| &row.uuid);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<QuailEvent>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<QuailEvent>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `QuailEvent`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait quail_eventsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `QuailEvent`.
    fn quail_events(&self) -> __sdk::__query_builder::Table<QuailEvent>;
}

impl quail_eventsQueryTableAccess for __sdk::QueryTableAccessor {
    fn quail_events(&self) -> __sdk::__query_builder::Table<QuailEvent> {
        __sdk::__query_builder::Table::new("quail_events")
    }
}
