// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.0.5 (commit 2dbec5ca66cb9d250f054de469443c2585c573d2).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetQuailPhotoArgs {
    pub quail_uuid: String,
    pub photo_uuid: Option<String>,
}

impl From<SetQuailPhotoArgs> for super::Reducer {
    fn from(args: SetQuailPhotoArgs) -> Self {
        Self::SetQuailPhoto {
            quail_uuid: args.quail_uuid,
            photo_uuid: args.photo_uuid,
        }
    }
}

impl __sdk::InModule for SetQuailPhotoArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_quail_photo`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_quail_photo {
    /// Request that the remote module invoke the reducer `set_quail_photo` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    ///
    /// Use [`set_quail_photo::set_quail_photo_then`] to run a callback after the reducer completes.
    fn set_quail_photo(&self, quail_uuid: String, photo_uuid: Option<String>) -> __sdk::Result<()> {
        self.set_quail_photo_then(quail_uuid, photo_uuid, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_quail_photo` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_quail_photo_then(
        &self,
        quail_uuid: String,
        photo_uuid: Option<String>,
        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl set_quail_photo for super::RemoteReducers {
    fn set_quail_photo_then(
        &self,
        quail_uuid: String,
        photo_uuid: Option<String>,
        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SetQuailPhotoArgs {
                quail_uuid,
                photo_uuid,
            },
            callback,
        )
    }
}
