// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.0.5 (commit 2dbec5ca66cb9d250f054de469443c2585c573d2).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::update_quail_args_type::UpdateQuailArgs as UpdateQuailArgsType;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateQuailArgs {
    pub args: UpdateQuailArgsType,
}

impl From<UpdateQuailArgs> for super::Reducer {
    fn from(args: UpdateQuailArgs) -> Self {
        Self::UpdateQuail { args: args.args }
    }
}

impl __sdk::InModule for UpdateQuailArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_quail`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_quail {
    /// Request that the remote module invoke the reducer `update_quail` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    ///
    /// Use [`update_quail::update_quail_then`] to run a callback after the reducer completes.
    fn update_quail(&self, args: UpdateQuailArgsType) -> __sdk::Result<()> {
        self.update_quail_then(args, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_quail` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_quail_then(
        &self,
        args: UpdateQuailArgsType,
        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl update_quail for super::RemoteReducers {
    fn update_quail_then(
        &self,
        args: UpdateQuailArgsType,
        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(UpdateQuailArgs { args }, callback)
    }
}
