// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct UpdatePhotoVersionArgs {
    pub uuid: String,
    pub version: i32,
    pub is_original: bool,
    pub relative_path: String,
}

impl __sdk::InModule for UpdatePhotoVersionArgs {
    type Module = super::RemoteModule;
}
