// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.0.5 (commit 2dbec5ca66cb9d250f054de469443c2585c573d2).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::update_photo_version_args_type::UpdatePhotoVersionArgs as UpdatePhotoVersionArgsType;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdatePhotoVersionArgs {
    pub args: UpdatePhotoVersionArgsType,
}

impl From<UpdatePhotoVersionArgs> for super::Reducer {
    fn from(args: UpdatePhotoVersionArgs) -> Self {
        Self::UpdatePhotoVersion { args: args.args }
    }
}

impl __sdk::InModule for UpdatePhotoVersionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_photo_version`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_photo_version {
    /// Request that the remote module invoke the reducer `update_photo_version` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    ///
    /// Use [`update_photo_version::update_photo_version_then`] to run a callback after the reducer completes.
    fn update_photo_version(&self, args: UpdatePhotoVersionArgsType) -> __sdk::Result<()> {
        self.update_photo_version_then(args, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_photo_version` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_photo_version_then(
        &self,
        args: UpdatePhotoVersionArgsType,
        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl update_photo_version for super::RemoteReducers {
    fn update_photo_version_then(
        &self,
        args: UpdatePhotoVersionArgsType,
        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(UpdatePhotoVersionArgs { args }, callback)
    }
}
