// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct UpdatePhotoSyncStatusArgs {
    pub uuid: String,
    pub sync_status: String,
    pub sync_error: Option<String>,
    pub last_sync_attempt: Option<i64>,
    pub retry_count: i32,
}

impl __sdk::InModule for UpdatePhotoSyncStatusArgs {
    type Module = super::RemoteModule;
}
