// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.0.3 (commit 62812a0ed757d82548fcd15b51a6ffda659f80c2).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::update_photo_collection_args_type::UpdatePhotoCollectionArgs as UpdatePhotoCollectionArgsType;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdatePhotoCollectionArgs {
    pub args: UpdatePhotoCollectionArgsType,
}

impl From<UpdatePhotoCollectionArgs> for super::Reducer {
    fn from(args: UpdatePhotoCollectionArgs) -> Self {
        Self::UpdatePhotoCollection { args: args.args }
    }
}

impl __sdk::InModule for UpdatePhotoCollectionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_photo_collection`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_photo_collection {
    /// Request that the remote module invoke the reducer `update_photo_collection` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    ///
    /// Use [`update_photo_collection::update_photo_collection_then`] to run a callback after the reducer completes.
    fn update_photo_collection(&self, args: UpdatePhotoCollectionArgsType) -> __sdk::Result<()> {
        self.update_photo_collection_then(args, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_photo_collection` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_photo_collection_then(
        &self,
        args: UpdatePhotoCollectionArgsType,
        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl update_photo_collection for super::RemoteReducers {
    fn update_photo_collection_then(
        &self,
        args: UpdatePhotoCollectionArgsType,
        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(UpdatePhotoCollectionArgs { args }, callback)
    }
}
