// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CreatePhotoCollectionArgs {
    pub uuid: String,
    pub quail_uuid: Option<String>,
    pub event_uuid: Option<String>,
    pub name: String,
}

impl __sdk::InModule for CreatePhotoCollectionArgs {
    type Module = super::RemoteModule;
}
