// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DeleteEggRecordArgs {
    pub uuid: String,
}

impl From<DeleteEggRecordArgs> for super::Reducer {
    fn from(args: DeleteEggRecordArgs) -> Self {
        Self::DeleteEggRecord { uuid: args.uuid }
    }
}

impl __sdk::InModule for DeleteEggRecordArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `delete_egg_record`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait delete_egg_record {
    /// Request that the remote module invoke the reducer `delete_egg_record` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`delete_egg_record:delete_egg_record_then`] to run a callback after the reducer completes.
    fn delete_egg_record(&self, uuid: String) -> __sdk::Result<()> {
        self.delete_egg_record_then(uuid, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `delete_egg_record` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn delete_egg_record_then(
        &self,
        uuid: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl delete_egg_record for super::RemoteReducers {
    fn delete_egg_record_then(
        &self,
        uuid: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(DeleteEggRecordArgs { uuid }, callback)
    }
}
