// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.0.3 (commit 62812a0ed757d82548fcd15b51a6ffda659f80c2).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DeleteEventArgs {
    pub uuid: String,
}

impl From<DeleteEventArgs> for super::Reducer {
    fn from(args: DeleteEventArgs) -> Self {
        Self::DeleteEvent { uuid: args.uuid }
    }
}

impl __sdk::InModule for DeleteEventArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `delete_event`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait delete_event {
    /// Request that the remote module invoke the reducer `delete_event` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    ///
    /// Use [`delete_event::delete_event_then`] to run a callback after the reducer completes.
    fn delete_event(&self, uuid: String) -> __sdk::Result<()> {
        self.delete_event_then(uuid, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `delete_event` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn delete_event_then(
        &self,
        uuid: String,
        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl delete_event for super::RemoteReducers {
    fn delete_event_then(
        &self,
        uuid: String,
        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(DeleteEventArgs { uuid }, callback)
    }
}
