// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Device {
    pub device_id: String,
    pub name: Option<String>,
    pub comment: Option<String>,
    pub first_seen: i64,
    pub last_seen: i64,
    pub owner: String,
}

impl __sdk::InModule for Device {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Device`.
///
/// Provides typed access to columns for query building.
pub struct DeviceCols {
    pub device_id: __sdk::__query_builder::Col<Device, String>,
    pub name: __sdk::__query_builder::Col<Device, Option<String>>,
    pub comment: __sdk::__query_builder::Col<Device, Option<String>>,
    pub first_seen: __sdk::__query_builder::Col<Device, i64>,
    pub last_seen: __sdk::__query_builder::Col<Device, i64>,
    pub owner: __sdk::__query_builder::Col<Device, String>,
}

impl __sdk::__query_builder::HasCols for Device {
    type Cols = DeviceCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        DeviceCols {
            device_id: __sdk::__query_builder::Col::new(table_name, "device_id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            comment: __sdk::__query_builder::Col::new(table_name, "comment"),
            first_seen: __sdk::__query_builder::Col::new(table_name, "first_seen"),
            last_seen: __sdk::__query_builder::Col::new(table_name, "last_seen"),
            owner: __sdk::__query_builder::Col::new(table_name, "owner"),
        }
    }
}

/// Indexed column accessor struct for the table `Device`.
///
/// Provides typed access to indexed columns for query building.
pub struct DeviceIxCols {
    pub device_id: __sdk::__query_builder::IxCol<Device, String>,
}

impl __sdk::__query_builder::HasIxCols for Device {
    type IxCols = DeviceIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        DeviceIxCols {
            device_id: __sdk::__query_builder::IxCol::new(table_name, "device_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Device {}
