// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.0.3 (commit 62812a0ed757d82548fcd15b51a6ffda659f80c2).

#![allow(unused, clippy::all)]

//! Dioxus v0.7 signals and hooks for SpacetimeDB integration.

use super::*;
use ::dioxus::prelude::*;
use ::dioxus::signals::SyncSignal;
use spacetimedb_sdk::{DbContext, Identity, Table, TableWithPrimaryKey};
use std::sync::Arc;

/// Thread-safe wrapper for the database connection.
pub type SharedConnection = Arc<DbConnection>;

/// Container for all table signals, created at root level.
#[derive(Clone)]
pub struct TableSignals {
    pub egg_records: SyncSignal<Vec<EggRecord>>,
    pub photo_collections: SyncSignal<Vec<PhotoCollection>>,
    pub photos: SyncSignal<Vec<Photo>>,
    pub quail_events: SyncSignal<Vec<QuailEvent>>,
    pub quails: SyncSignal<Vec<Quail>>,
}

/// Internal state for managing the SpacetimeDB connection.
#[derive(Clone)]
pub struct SpacetimeDbContext {
    /// The database connection (wrapped in Arc for thread-safety).
    pub connection: SyncSignal<Option<SharedConnection>>,
    /// The current connection state.
    pub state: SyncSignal<ConnectionState>,
    /// Error from the last connection attempt, if any.
    pub error: SyncSignal<Option<String>>,
    /// All table signals, created at root level.
    pub tables: TableSignals,
}

/// The current state of the SpacetimeDB connection.
#[derive(Clone, PartialEq, Eq, Debug, Default)]
pub enum ConnectionState {
    #[default]
    Disconnected,
    Connecting,
    /// Connected includes the `Identity` assigned by the server and a private access token (JWT)
    /// which can be persisted by the application for future reconnection as the same Identity.
    Connected(Identity, String),
    Error,
}

/// Initialize the SpacetimeDB context provider at the root of your application.
///
/// This hook must be called at the root component before using any other SpacetimeDB hooks.
/// It creates all table signals at root level to ensure they outlive child components.
///
/// # Arguments
/// * `uri` - The SpacetimeDB server URI
/// * `module_name` - The module name to connect to
/// * `token` - An optional OpenID Connect compliant JSON Web Token (JWT) for authentication.
///   If `None` is passed or this method is not called, SpacetimeDB will generate a new Identity
///   and sign a new private access token for the connection.
#[must_use]
pub fn use_spacetimedb_context_provider(
    uri: &str,
    module_name: &str,
    token: Option<impl ToString>,
) -> SpacetimeDbContext {
    let uri = uri.to_string();
    let module_name = module_name.to_string();
    let token = token.map(|t| t.to_string());

    let connection: SyncSignal<Option<SharedConnection>> = use_signal_sync(|| None);
    let state: SyncSignal<ConnectionState> = use_signal_sync(|| ConnectionState::Disconnected);
    let error: SyncSignal<Option<String>> = use_signal_sync(|| None);

    let mut table_signals = TableSignals {
        egg_records: use_signal_sync(Vec::new),
        photo_collections: use_signal_sync(Vec::new),
        photos: use_signal_sync(Vec::new),
        quail_events: use_signal_sync(Vec::new),
        quails: use_signal_sync(Vec::new),
    };

    let ctx = SpacetimeDbContext {
        connection,
        state,
        error,
        tables: table_signals.clone(),
    };

    use_context_provider(|| ctx.clone());

    use_effect(move || {
        let mut connection = connection;
        let mut state = state;
        let mut error = error;
        let uri = uri.clone();
        let mut module_name = module_name.clone();
        let token = token.clone();
        let mut table_signals = table_signals.clone();

        state.set(ConnectionState::Connecting);

        spawn(async move {
            match DbConnection::builder()
                .with_uri(&uri)
                .with_database_name(&module_name)
                .with_token(token)
                .on_connect(move |conn, identity, token| {
                    // Populate initial rows for egg_records
                    let current: Vec<EggRecord> = conn.db.egg_records().iter().collect();
                    table_signals.egg_records.set(current);

                    // Keep signal in sync on changes
                    conn.db.egg_records().on_insert(move |ctx, _row| {
                        let updated: Vec<EggRecord> = ctx.db.egg_records().iter().collect();
                        table_signals.egg_records.set(updated);
                    });
                    conn.db.egg_records().on_update(move |ctx, _old, _new| {
                        let updated: Vec<EggRecord> = ctx.db.egg_records().iter().collect();
                        table_signals.egg_records.set(updated);
                    });
                    conn.db.egg_records().on_delete(move |ctx, _row| {
                        let updated: Vec<EggRecord> = ctx.db.egg_records().iter().collect();
                        table_signals.egg_records.set(updated);
                    });
                    // Populate initial rows for photo_collections
                    let current: Vec<PhotoCollection> =
                        conn.db.photo_collections().iter().collect();
                    table_signals.photo_collections.set(current);

                    // Keep signal in sync on changes
                    conn.db.photo_collections().on_insert(move |ctx, _row| {
                        let updated: Vec<PhotoCollection> =
                            ctx.db.photo_collections().iter().collect();
                        table_signals.photo_collections.set(updated);
                    });
                    conn.db
                        .photo_collections()
                        .on_update(move |ctx, _old, _new| {
                            let updated: Vec<PhotoCollection> =
                                ctx.db.photo_collections().iter().collect();
                            table_signals.photo_collections.set(updated);
                        });
                    conn.db.photo_collections().on_delete(move |ctx, _row| {
                        let updated: Vec<PhotoCollection> =
                            ctx.db.photo_collections().iter().collect();
                        table_signals.photo_collections.set(updated);
                    });
                    // Populate initial rows for photos
                    let current: Vec<Photo> = conn.db.photos().iter().collect();
                    table_signals.photos.set(current);

                    // Keep signal in sync on changes
                    conn.db.photos().on_insert(move |ctx, _row| {
                        let updated: Vec<Photo> = ctx.db.photos().iter().collect();
                        table_signals.photos.set(updated);
                    });
                    conn.db.photos().on_update(move |ctx, _old, _new| {
                        let updated: Vec<Photo> = ctx.db.photos().iter().collect();
                        table_signals.photos.set(updated);
                    });
                    conn.db.photos().on_delete(move |ctx, _row| {
                        let updated: Vec<Photo> = ctx.db.photos().iter().collect();
                        table_signals.photos.set(updated);
                    });
                    // Populate initial rows for quail_events
                    let current: Vec<QuailEvent> = conn.db.quail_events().iter().collect();
                    table_signals.quail_events.set(current);

                    // Keep signal in sync on changes
                    conn.db.quail_events().on_insert(move |ctx, _row| {
                        let updated: Vec<QuailEvent> = ctx.db.quail_events().iter().collect();
                        table_signals.quail_events.set(updated);
                    });
                    conn.db.quail_events().on_update(move |ctx, _old, _new| {
                        let updated: Vec<QuailEvent> = ctx.db.quail_events().iter().collect();
                        table_signals.quail_events.set(updated);
                    });
                    conn.db.quail_events().on_delete(move |ctx, _row| {
                        let updated: Vec<QuailEvent> = ctx.db.quail_events().iter().collect();
                        table_signals.quail_events.set(updated);
                    });
                    // Populate initial rows for quails
                    let current: Vec<Quail> = conn.db.quails().iter().collect();
                    table_signals.quails.set(current);

                    // Keep signal in sync on changes
                    conn.db.quails().on_insert(move |ctx, _row| {
                        let updated: Vec<Quail> = ctx.db.quails().iter().collect();
                        table_signals.quails.set(updated);
                    });
                    conn.db.quails().on_update(move |ctx, _old, _new| {
                        let updated: Vec<Quail> = ctx.db.quails().iter().collect();
                        table_signals.quails.set(updated);
                    });
                    conn.db.quails().on_delete(move |ctx, _row| {
                        let updated: Vec<Quail> = ctx.db.quails().iter().collect();
                        table_signals.quails.set(updated);
                    });
                    // Store the assigned Identity and private access token in state so the app
                    // can persist the token (JWT) and reuse it for future reconnections via `with_token`.
                    state.set(ConnectionState::Connected(identity, token.to_string()));
                })
                .on_disconnect(move |_ctx, err: Option<spacetimedb_sdk::Error>| {
                    if let Some(e) = err {
                        error.set(Some::<String>(e.to_string()));
                        state.set(ConnectionState::Error);
                    } else {
                        state.set(ConnectionState::Disconnected);
                    }
                })
                .build()
            {
                Ok(conn) => {
                    let shared_conn: Arc<DbConnection> = Arc::new(conn);
                    connection.set(Some(shared_conn.clone()));

                    spawn(async move {
                        let _ = shared_conn.run_async().await;
                    });
                }
                Err(e) => {
                    error.set(Some::<String>(e.to_string()));
                    state.set(ConnectionState::Error);
                }
            }
        });
    });

    ctx
}

/// Get the SpacetimeDB context from a parent component.
#[must_use]
pub fn use_spacetimedb_context() -> SpacetimeDbContext {
    use_context::<SpacetimeDbContext>()
}

/// Get the current database connection, if connected.
#[must_use]
pub fn use_connection() -> SyncSignal<Option<SharedConnection>> {
    let ctx = use_spacetimedb_context();
    ctx.connection
}

/// Subscribe to a set of SQL queries.
pub fn use_subscription(queries: &[&str]) {
    let queries: Vec<String> = queries.iter().map(|s| s.to_string()).collect();
    let conn_signal = use_connection();

    use_effect(move || {
        let queries = queries.clone();
        if let Some(conn) = conn_signal.read().as_ref() {
            conn.subscription_builder()
                .on_applied(|_ctx| {})
                .on_error(|_ctx, _err| {})
                .subscribe(queries);
        }
    });
}

// --- Table hooks ---

/// Get a reactive signal containing all rows of the `egg_records` table.
#[must_use]
pub fn use_table_egg_records() -> SyncSignal<Vec<EggRecord>> {
    let ctx = use_spacetimedb_context();
    ctx.tables.egg_records
}

/// Get a reactive signal containing all rows of the `photo_collections` table.
#[must_use]
pub fn use_table_photo_collections() -> SyncSignal<Vec<PhotoCollection>> {
    let ctx = use_spacetimedb_context();
    ctx.tables.photo_collections
}

/// Get a reactive signal containing all rows of the `photos` table.
#[must_use]
pub fn use_table_photos() -> SyncSignal<Vec<Photo>> {
    let ctx = use_spacetimedb_context();
    ctx.tables.photos
}

/// Get a reactive signal containing all rows of the `quail_events` table.
#[must_use]
pub fn use_table_quail_events() -> SyncSignal<Vec<QuailEvent>> {
    let ctx = use_spacetimedb_context();
    ctx.tables.quail_events
}

/// Get a reactive signal containing all rows of the `quails` table.
#[must_use]
pub fn use_table_quails() -> SyncSignal<Vec<Quail>> {
    let ctx = use_spacetimedb_context();
    ctx.tables.quails
}

// --- Reducer hooks ---

/// Get a callback to invoke the `create_event` reducer.
#[must_use]
pub fn use_reducer_create_event(
) -> impl Fn(create_event_args_type::CreateEventArgs) + Clone + 'static {
    let conn_signal = use_connection();

    move |args: create_event_args_type::CreateEventArgs| {
        if let Some(conn) = conn_signal.read().as_ref() {
            let _ = conn.reducers.create_event(args);
        }
    }
}

/// Get a callback to invoke the `create_photo` reducer.
#[must_use]
pub fn use_reducer_create_photo(
) -> impl Fn(create_photo_args_type::CreatePhotoArgs) + Clone + 'static {
    let conn_signal = use_connection();

    move |args: create_photo_args_type::CreatePhotoArgs| {
        if let Some(conn) = conn_signal.read().as_ref() {
            let _ = conn.reducers.create_photo(args);
        }
    }
}

/// Get a callback to invoke the `create_photo_collection` reducer.
#[must_use]
pub fn use_reducer_create_photo_collection(
) -> impl Fn(create_photo_collection_args_type::CreatePhotoCollectionArgs) + Clone + 'static {
    let conn_signal = use_connection();

    move |args: create_photo_collection_args_type::CreatePhotoCollectionArgs| {
        if let Some(conn) = conn_signal.read().as_ref() {
            let _ = conn.reducers.create_photo_collection(args);
        }
    }
}

/// Get a callback to invoke the `create_quail` reducer.
#[must_use]
pub fn use_reducer_create_quail(
) -> impl Fn(create_quail_args_type::CreateQuailArgs) + Clone + 'static {
    let conn_signal = use_connection();

    move |args: create_quail_args_type::CreateQuailArgs| {
        if let Some(conn) = conn_signal.read().as_ref() {
            let _ = conn.reducers.create_quail(args);
        }
    }
}

/// Get a callback to invoke the `delete_egg_record` reducer.
#[must_use]
pub fn use_reducer_delete_egg_record() -> impl Fn(String) + Clone + 'static {
    let conn_signal = use_connection();

    move |uuid: String| {
        if let Some(conn) = conn_signal.read().as_ref() {
            let _ = conn.reducers.delete_egg_record(uuid);
        }
    }
}

/// Get a callback to invoke the `delete_event` reducer.
#[must_use]
pub fn use_reducer_delete_event() -> impl Fn(String) + Clone + 'static {
    let conn_signal = use_connection();

    move |uuid: String| {
        if let Some(conn) = conn_signal.read().as_ref() {
            let _ = conn.reducers.delete_event(uuid);
        }
    }
}

/// Get a callback to invoke the `delete_photo` reducer.
#[must_use]
pub fn use_reducer_delete_photo() -> impl Fn(String) + Clone + 'static {
    let conn_signal = use_connection();

    move |uuid: String| {
        if let Some(conn) = conn_signal.read().as_ref() {
            let _ = conn.reducers.delete_photo(uuid);
        }
    }
}

/// Get a callback to invoke the `delete_photo_collection` reducer.
#[must_use]
pub fn use_reducer_delete_photo_collection() -> impl Fn(String) + Clone + 'static {
    let conn_signal = use_connection();

    move |uuid: String| {
        if let Some(conn) = conn_signal.read().as_ref() {
            let _ = conn.reducers.delete_photo_collection(uuid);
        }
    }
}

/// Get a callback to invoke the `delete_quail` reducer.
#[must_use]
pub fn use_reducer_delete_quail() -> impl Fn(String) + Clone + 'static {
    let conn_signal = use_connection();

    move |uuid: String| {
        if let Some(conn) = conn_signal.read().as_ref() {
            let _ = conn.reducers.delete_quail(uuid);
        }
    }
}

/// Get a callback to invoke the `set_quail_photo` reducer.
#[must_use]
pub fn use_reducer_set_quail_photo() -> impl Fn(String, Option<String>) + Clone + 'static {
    let conn_signal = use_connection();

    move |quail_uuid: String, photo_uuid: Option<String>| {
        if let Some(conn) = conn_signal.read().as_ref() {
            let _ = conn.reducers.set_quail_photo(quail_uuid, photo_uuid);
        }
    }
}

/// Get a callback to invoke the `update_event` reducer.
#[must_use]
pub fn use_reducer_update_event(
) -> impl Fn(update_event_args_type::UpdateEventArgs) + Clone + 'static {
    let conn_signal = use_connection();

    move |args: update_event_args_type::UpdateEventArgs| {
        if let Some(conn) = conn_signal.read().as_ref() {
            let _ = conn.reducers.update_event(args);
        }
    }
}

/// Get a callback to invoke the `update_photo_collection` reducer.
#[must_use]
pub fn use_reducer_update_photo_collection(
) -> impl Fn(update_photo_collection_args_type::UpdatePhotoCollectionArgs) + Clone + 'static {
    let conn_signal = use_connection();

    move |args: update_photo_collection_args_type::UpdatePhotoCollectionArgs| {
        if let Some(conn) = conn_signal.read().as_ref() {
            let _ = conn.reducers.update_photo_collection(args);
        }
    }
}

/// Get a callback to invoke the `update_photo_sync_status` reducer.
#[must_use]
pub fn use_reducer_update_photo_sync_status(
) -> impl Fn(update_photo_sync_status_args_type::UpdatePhotoSyncStatusArgs) + Clone + 'static {
    let conn_signal = use_connection();

    move |args: update_photo_sync_status_args_type::UpdatePhotoSyncStatusArgs| {
        if let Some(conn) = conn_signal.read().as_ref() {
            let _ = conn.reducers.update_photo_sync_status(args);
        }
    }
}

/// Get a callback to invoke the `update_quail` reducer.
#[must_use]
pub fn use_reducer_update_quail(
) -> impl Fn(update_quail_args_type::UpdateQuailArgs) + Clone + 'static {
    let conn_signal = use_connection();

    move |args: update_quail_args_type::UpdateQuailArgs| {
        if let Some(conn) = conn_signal.read().as_ref() {
            let _ = conn.reducers.update_quail(args);
        }
    }
}

/// Get a callback to invoke the `upsert_egg_record` reducer.
#[must_use]
pub fn use_reducer_upsert_egg_record(
) -> impl Fn(upsert_egg_record_args_type::UpsertEggRecordArgs) + Clone + 'static {
    let conn_signal = use_connection();

    move |args: upsert_egg_record_args_type::UpsertEggRecordArgs| {
        if let Some(conn) = conn_signal.read().as_ref() {
            let _ = conn.reducers.upsert_egg_record(args);
        }
    }
}

// --- Connection state hooks ---

/// Get a reactive signal for the current connection state.
#[must_use]
pub fn use_connection_state() -> SyncSignal<ConnectionState> {
    let ctx = use_spacetimedb_context();
    ctx.state
}

/// Get a reactive signal for the current connection error, if any.
#[must_use]
pub fn use_connection_error() -> SyncSignal<Option<String>> {
    let ctx = use_spacetimedb_context();
    ctx.error
}
