// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct EggRecord {
    pub uuid: String,
    pub id: u64,
    pub record_date: String,
    pub total_eggs: i32,
    pub notes: Option<String>,
    pub device_id: String,
    pub owner: String,
}

impl __sdk::InModule for EggRecord {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `EggRecord`.
///
/// Provides typed access to columns for query building.
pub struct EggRecordCols {
    pub uuid: __sdk::__query_builder::Col<EggRecord, String>,
    pub id: __sdk::__query_builder::Col<EggRecord, u64>,
    pub record_date: __sdk::__query_builder::Col<EggRecord, String>,
    pub total_eggs: __sdk::__query_builder::Col<EggRecord, i32>,
    pub notes: __sdk::__query_builder::Col<EggRecord, Option<String>>,
    pub device_id: __sdk::__query_builder::Col<EggRecord, String>,
    pub owner: __sdk::__query_builder::Col<EggRecord, String>,
}

impl __sdk::__query_builder::HasCols for EggRecord {
    type Cols = EggRecordCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        EggRecordCols {
            uuid: __sdk::__query_builder::Col::new(table_name, "uuid"),
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            record_date: __sdk::__query_builder::Col::new(table_name, "record_date"),
            total_eggs: __sdk::__query_builder::Col::new(table_name, "total_eggs"),
            notes: __sdk::__query_builder::Col::new(table_name, "notes"),
            device_id: __sdk::__query_builder::Col::new(table_name, "device_id"),
            owner: __sdk::__query_builder::Col::new(table_name, "owner"),
        }
    }
}

/// Indexed column accessor struct for the table `EggRecord`.
///
/// Provides typed access to indexed columns for query building.
pub struct EggRecordIxCols {
    pub uuid: __sdk::__query_builder::IxCol<EggRecord, String>,
}

impl __sdk::__query_builder::HasIxCols for EggRecord {
    type IxCols = EggRecordIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        EggRecordIxCols {
            uuid: __sdk::__query_builder::IxCol::new(table_name, "uuid"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for EggRecord {}
