// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PhotoCollection {
    pub uuid: String,
    pub id: u64,
    pub quail_uuid: Option<String>,
    pub event_uuid: Option<String>,
    pub preview_photo_uuid: Option<String>,
    pub name: String,
    pub owner: String,
}

impl __sdk::InModule for PhotoCollection {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PhotoCollection`.
///
/// Provides typed access to columns for query building.
pub struct PhotoCollectionCols {
    pub uuid: __sdk::__query_builder::Col<PhotoCollection, String>,
    pub id: __sdk::__query_builder::Col<PhotoCollection, u64>,
    pub quail_uuid: __sdk::__query_builder::Col<PhotoCollection, Option<String>>,
    pub event_uuid: __sdk::__query_builder::Col<PhotoCollection, Option<String>>,
    pub preview_photo_uuid: __sdk::__query_builder::Col<PhotoCollection, Option<String>>,
    pub name: __sdk::__query_builder::Col<PhotoCollection, String>,
    pub owner: __sdk::__query_builder::Col<PhotoCollection, String>,
}

impl __sdk::__query_builder::HasCols for PhotoCollection {
    type Cols = PhotoCollectionCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PhotoCollectionCols {
            uuid: __sdk::__query_builder::Col::new(table_name, "uuid"),
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            quail_uuid: __sdk::__query_builder::Col::new(table_name, "quail_uuid"),
            event_uuid: __sdk::__query_builder::Col::new(table_name, "event_uuid"),
            preview_photo_uuid: __sdk::__query_builder::Col::new(table_name, "preview_photo_uuid"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            owner: __sdk::__query_builder::Col::new(table_name, "owner"),
        }
    }
}

/// Indexed column accessor struct for the table `PhotoCollection`.
///
/// Provides typed access to indexed columns for query building.
pub struct PhotoCollectionIxCols {
    pub uuid: __sdk::__query_builder::IxCol<PhotoCollection, String>,
}

impl __sdk::__query_builder::HasIxCols for PhotoCollection {
    type IxCols = PhotoCollectionIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PhotoCollectionIxCols {
            uuid: __sdk::__query_builder::IxCol::new(table_name, "uuid"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PhotoCollection {}
