// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::quail_type::Quail;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `quails`.
///
/// Obtain a handle from the [`QuailsTableAccess::quails`] method on [`super::RemoteTables`],
/// like `ctx.db.quails()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.quails().on_insert(...)`.
pub struct QuailsTableHandle<'ctx> {
    imp: __sdk::TableHandle<Quail>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `quails`.
///
/// Implemented for [`super::RemoteTables`].
pub trait QuailsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`QuailsTableHandle`], which mediates access to the table `quails`.
    fn quails(&self) -> QuailsTableHandle<'_>;
}

impl QuailsTableAccess for super::RemoteTables {
    fn quails(&self) -> QuailsTableHandle<'_> {
        QuailsTableHandle {
            imp: self.imp.get_table::<Quail>("quails"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct QuailsInsertCallbackId(__sdk::CallbackId);
pub struct QuailsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for QuailsTableHandle<'ctx> {
    type Row = Quail;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Quail> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = QuailsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> QuailsInsertCallbackId {
        QuailsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: QuailsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = QuailsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> QuailsDeleteCallbackId {
        QuailsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: QuailsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct QuailsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for QuailsTableHandle<'ctx> {
    type UpdateCallbackId = QuailsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> QuailsUpdateCallbackId {
        QuailsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: QuailsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `uuid` unique index on the table `quails`,
/// which allows point queries on the field of the same name
/// via the [`QuailsUuidUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.quails().uuid().find(...)`.
pub struct QuailsUuidUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Quail, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> QuailsTableHandle<'ctx> {
    /// Get a handle on the `uuid` unique index on the table `quails`.
    pub fn uuid(&self) -> QuailsUuidUnique<'ctx> {
        QuailsUuidUnique {
            imp: self.imp.get_unique_constraint::<String>("uuid"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> QuailsUuidUnique<'ctx> {
    /// Find the subscribed row whose `uuid` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<Quail> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Quail>("quails");
    _table.add_unique_constraint::<String>("uuid", |row| &row.uuid);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Quail>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Quail>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Quail`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait quailsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Quail`.
    fn quails(&self) -> __sdk::__query_builder::Table<Quail>;
}

impl quailsQueryTableAccess for __sdk::QueryTableAccessor {
    fn quails(&self) -> __sdk::__query_builder::Table<Quail> {
        __sdk::__query_builder::Table::new("quails")
    }
}
