// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Quail {
    pub uuid: String,
    pub name: String,
    pub gender: String,
    pub ring_color: Option<String>,
    pub profile_photo: Option<String>,
    pub birthday: Option<String>,
    pub device_id: String,
    pub owner: String,
    pub created_at: i64,
}

impl __sdk::InModule for Quail {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Quail`.
///
/// Provides typed access to columns for query building.
pub struct QuailCols {
    pub uuid: __sdk::__query_builder::Col<Quail, String>,
    pub name: __sdk::__query_builder::Col<Quail, String>,
    pub gender: __sdk::__query_builder::Col<Quail, String>,
    pub ring_color: __sdk::__query_builder::Col<Quail, Option<String>>,
    pub profile_photo: __sdk::__query_builder::Col<Quail, Option<String>>,
    pub birthday: __sdk::__query_builder::Col<Quail, Option<String>>,
    pub device_id: __sdk::__query_builder::Col<Quail, String>,
    pub owner: __sdk::__query_builder::Col<Quail, String>,
    pub created_at: __sdk::__query_builder::Col<Quail, i64>,
}

impl __sdk::__query_builder::HasCols for Quail {
    type Cols = QuailCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        QuailCols {
            uuid: __sdk::__query_builder::Col::new(table_name, "uuid"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            gender: __sdk::__query_builder::Col::new(table_name, "gender"),
            ring_color: __sdk::__query_builder::Col::new(table_name, "ring_color"),
            profile_photo: __sdk::__query_builder::Col::new(table_name, "profile_photo"),
            birthday: __sdk::__query_builder::Col::new(table_name, "birthday"),
            device_id: __sdk::__query_builder::Col::new(table_name, "device_id"),
            owner: __sdk::__query_builder::Col::new(table_name, "owner"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
        }
    }
}

/// Indexed column accessor struct for the table `Quail`.
///
/// Provides typed access to indexed columns for query building.
pub struct QuailIxCols {
    pub uuid: __sdk::__query_builder::IxCol<Quail, String>,
}

impl __sdk::__query_builder::HasIxCols for Quail {
    type IxCols = QuailIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        QuailIxCols {
            uuid: __sdk::__query_builder::IxCol::new(table_name, "uuid"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Quail {}
