// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct QuailEvent {
    pub uuid: String,
    pub id: u64,
    pub quail_uuid: String,
    pub event_type: String,
    pub event_date: String,
    pub notes: Option<String>,
    pub photos: Option<String>,
    pub device_id: String,
    pub owner: String,
}

impl __sdk::InModule for QuailEvent {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `QuailEvent`.
///
/// Provides typed access to columns for query building.
pub struct QuailEventCols {
    pub uuid: __sdk::__query_builder::Col<QuailEvent, String>,
    pub id: __sdk::__query_builder::Col<QuailEvent, u64>,
    pub quail_uuid: __sdk::__query_builder::Col<QuailEvent, String>,
    pub event_type: __sdk::__query_builder::Col<QuailEvent, String>,
    pub event_date: __sdk::__query_builder::Col<QuailEvent, String>,
    pub notes: __sdk::__query_builder::Col<QuailEvent, Option<String>>,
    pub photos: __sdk::__query_builder::Col<QuailEvent, Option<String>>,
    pub device_id: __sdk::__query_builder::Col<QuailEvent, String>,
    pub owner: __sdk::__query_builder::Col<QuailEvent, String>,
}

impl __sdk::__query_builder::HasCols for QuailEvent {
    type Cols = QuailEventCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        QuailEventCols {
            uuid: __sdk::__query_builder::Col::new(table_name, "uuid"),
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            quail_uuid: __sdk::__query_builder::Col::new(table_name, "quail_uuid"),
            event_type: __sdk::__query_builder::Col::new(table_name, "event_type"),
            event_date: __sdk::__query_builder::Col::new(table_name, "event_date"),
            notes: __sdk::__query_builder::Col::new(table_name, "notes"),
            photos: __sdk::__query_builder::Col::new(table_name, "photos"),
            device_id: __sdk::__query_builder::Col::new(table_name, "device_id"),
            owner: __sdk::__query_builder::Col::new(table_name, "owner"),
        }
    }
}

/// Indexed column accessor struct for the table `QuailEvent`.
///
/// Provides typed access to indexed columns for query building.
pub struct QuailEventIxCols {
    pub uuid: __sdk::__query_builder::IxCol<QuailEvent, String>,
}

impl __sdk::__query_builder::HasIxCols for QuailEvent {
    type IxCols = QuailEventIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        QuailEventIxCols {
            uuid: __sdk::__query_builder::IxCol::new(table_name, "uuid"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for QuailEvent {}
