// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.0.3 (commit 62812a0ed757d82548fcd15b51a6ffda659f80c2).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::update_event_args_type::UpdateEventArgs as UpdateEventArgsType;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateEventArgs {
    pub args: UpdateEventArgsType,
}

impl From<UpdateEventArgs> for super::Reducer {
    fn from(args: UpdateEventArgs) -> Self {
        Self::UpdateEvent { args: args.args }
    }
}

impl __sdk::InModule for UpdateEventArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_event`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_event {
    /// Request that the remote module invoke the reducer `update_event` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    ///
    /// Use [`update_event::update_event_then`] to run a callback after the reducer completes.
    fn update_event(&self, args: UpdateEventArgsType) -> __sdk::Result<()> {
        self.update_event_then(args, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_event` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_event_then(
        &self,
        args: UpdateEventArgsType,
        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_event for super::RemoteReducers {
    fn update_event_then(
        &self,
        args: UpdateEventArgsType,
        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(UpdateEventArgs { args }, callback)
    }
}
