//! Remote type definitions that mirror the SpacetimeDB server table rows.
//!
//! These types are normally auto-generated by `spacetime generate --lang rust`
//! (or `--lang dioxus`).  Until the Dioxus binding generator is available we
//! maintain them by hand.  Keep them in sync with `stalltagebuch-server/src/lib.rs`.

use serde::{Deserialize, Serialize};

/// Mirror of the `quails` table row.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct RemoteQuail {
    pub id: u64,
    pub uuid: String,
    pub name: String,
    pub gender: String,
    pub ring_color: Option<String>,
    pub profile_photo: Option<String>,
    pub owner: String,
}

/// Mirror of the `quail_events` table row.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct RemoteQuailEvent {
    pub id: u64,
    pub uuid: String,
    pub quail_uuid: String,
    pub event_type: String,
    pub event_date: String,
    pub notes: Option<String>,
    pub photos: Option<String>,
    pub owner: String,
}

/// Mirror of the `egg_records` table row.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct RemoteEggRecord {
    pub id: u64,
    pub uuid: String,
    pub record_date: String,
    pub total_eggs: i32,
    pub notes: Option<String>,
    pub owner: String,
}
